### PR TITLE
Fix main tour

### LINKED ISSUE #726: Tour for Entries doesn't look right
Have a look at the picture below:

image

### PR DESCRIPTION
**Pull request by ArsalanSavand**
# Bug fixes
Fixes #726

### CODE REVIEW

File: app/main/main_controller.js [hunk 1]
```diff
@@ -88,6 +88,15 @@ function MainController($scope, $rootScope, $state, $stateParams, AuthService, A
       );
     }
   };
+  
+  /**
+   * @desc Check if comments and entries are loaded
+   */
+  function Check() {
```
Comment (AmirSavand) [inline app/main/main_controller.js]: Rename.
