### PR TITLE
Fix entry toolbar editor

### LINKED ISSUE #444: Fix editor toolbar on mobile

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #444

### CODE REVIEW

File: app/basement/codekit/codekit_service.js [hunk 1]
```diff
@@ -188,6 +188,16 @@ function Codekit($timeout, $window) {
...
   }
 
+  /**
+   * @method isMobile
+   * @desc Check screen size to see if mobile or not
+   *
+   * @returns {Boolean}
+   */
+  function isMobile() {
+    return $window.matchMedia("only screen and (max-width: 760px)").matches;
```
Comment (Alir3z4) [inline app/basement/codekit/codekit_service.js]: @AmirSavand it's gonna warn user about the screen size ?
an alert or something ?
