### PR TITLE
Fix user settings not update

### LINKED ISSUE #1210: Fix user settings not updating

### LINKED ISSUE #1211: Fix sidebar not closing on new blog page

### LINKED ISSUE #1212: Remove sidebar page indicator

### LINKED ISSUE #1213: Fix profile completion conditions

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #1213 
Fixes #1212 
Fixes #1210 
Fixes #1211

### CODE REVIEW

File: src/app/account/user/user_controller.js [hunk 1]
```diff
@@ -40,20 +40,22 @@ function UserController($scope, $rootScope, $stateParams,
...
+      $scope.user.get.media.thumbnail_48x48 = null;
+      $scope.user.get.media.thumbnail_128x128 = null;
+      $scope.user.get.media.thumbnail_256x256 = null;
       payload.picture = null;
     }
 
     API.UserUpdate.patch(payload,
       function (data) {
-        if (removeAvatar) {
-          $scope.user.get.media = null;
```
Comment (AmirSavand) [inline src/app/account/user/user_controller.js]: You didn't cover this part.

File: src/app/main/main_controller.js [hunk 2]
```diff
@@ -13,6 +13,19 @@ function MainController($scope, $rootScope, $state, $stateParams,
     $scope.param = $stateParams;
     $scope.user = AuthService.getAuthenticatedUser(true);
 
+    $scope.isProfileCompleted = false;
+
+    API.User.get({
+        user_id: $scope.user.get.id
+      },
+      function (data) {
+        $scope.userInformation = data;
```
Comment (AmirSavand) [inline src/app/main/main_controller.js]: Rename to `userSettings`

File: src/app/main/main_controller.js [hunk 3]
```diff
@@ -13,6 +13,19 @@ function MainController($scope, $rootScope, $state, $stateParams,
     $scope.param = $stateParams;
     $scope.user = AuthService.getAuthenticatedUser(true);
 
+    $scope.isProfileCompleted = false;
+
+    API.User.get({
+        user_id: $scope.user.get.id
```
Comment (AmirSavand) [inline src/app/main/main_controller.js]: Keep this in one line.
