### PR TITLE
Email confirmation

### LINKED ISSUE #278: Forgot password link doesn't work !

### PR DESCRIPTION
**Pull request by ArsalanSavand**
- [x] Loading
- [x] Error
- [x] Resend link

Fixes #278

### CODE REVIEW

File: app/api/api_service.js [hunk 1]
```diff
@@ -120,9 +123,9 @@ function API($http, $resource, ENV) {
 
   function createResourceObject(attrName, endpoint) {
     apiData[attrName] = $resource(endpoint, {}, {
-      put: { method: "PUT" },
-      post: { method: "POST" },
-      patch: { method: "PATCH" }
+      put: {method: "PUT"},
+      post: {method: "POST"},
+      patch: {method: "PATCH"}
```
Comment (amirm3hdi) [inline app/api/api_service.js]: @ArsalanSavand Revert them back to standard code format.

**Comment by amirm3hdi** [comment]
@ArsalanSavand Once the resend ability is on, you should make resend button work.

File: app/api/api_service.js (hunk 1 above)
Comment (amirm3hdi) [inline app/api/api_service.js]: I've done it
