### PR TITLE
Fix logout when no permission

### LINKED ISSUE #658: Remove "Theme and Layout" from main for team members
Just check if it has no value, the `ng-if` the hell out of it.

### LINKED ISSUE #674: Fix instant logout after signing in
Error will raise for template-config api

### PR DESCRIPTION
**Pull request by ArsalanSavand**
# Bug Fixes
Fixes #674 
Fixes #658

### CODE REVIEW

File: app/account/auth/auth_interceptor_service.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ function AuthInterceptorService($rootScope, $cookies, $q, ENV, Utils) {
   function responseError(response) {
     // Authentication check
     if (response.status === 403) {
-      if (JSON.stringify(response.data).indexOf(Utils.texts.noPermission) === -1) {
+      if (JSON.stringify(response.data).indexOf(Utils.texts.noPermission) !== -1) {
```
Comment (AmirSavand) [inline app/account/auth/auth_interceptor_service.js]: Revert this.
